allowBuilds:
  core-js: set this to true or false
  es5-ext: set this to true or false
  highlight.js: set this to true or false
  sharp: set this to true or false
  uglifyjs-webpack-plugin: set this to true or false
